# Generated by Django 6.0.1 on 2026-02-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Production', 'Production'), ('Reproduction', 'Reproduction'), ('Sample', 'Sample')], max_length=50)),
                ('fabric_type', models.CharField(choices=[('Domestic', 'Domestic'), ('Export Large', 'Export Large'), ('Export Small', 'Export Small')], max_length=50)),
                ('total_qty', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Approval', 'Approval'), ('No Approval', 'No Approval')], default='No Approval', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Production', 'Production'), ('Re-Production', 'Re-Production'), ('Sample', 'Sample'), ('Stickers', 'Stickers'), ('TFusing', 'TFusing'), ('TBilling', 'TBilling')], max_length=50)),
                ('total_qty', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
