# Generated by Django 6.0.1 on 2026-02-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=100)),
                ('customer_po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Production', 'Production'), ('Reproduction', 'Reproduction')], default='Production', max_length=50)),
                ('payment_terms', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=50)),
                ('order_by', models.CharField(blank=True, max_length=100, null=True)),
                ('style_no', models.CharField(max_length=100)),
                ('style_name', models.CharField(max_length=100)),
                ('combo', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quotations/')),
                ('total_qty', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=200)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('rate', models.FloatField()),
                ('amt', models.FloatField(blank=True, null=True)),
                ('confirmed_amt', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.quotation')),
            ],
        ),
        migrations.DeleteModel(
            name='JobCard',
        ),
        migrations.DeleteModel(
            name='JobQuotation',
        ),
    ]
