# Generated by Django 6.0.1 on 2026-02-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_quotation_quotationitem_delete_jobcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
