# Generated by Django 6.0.1 on 2026-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_quotation_quotation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='fabric_type',
            field=models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('Imported', 'Imported')], default='Domestic', max_length=20, null=True),
        ),
    ]
