# Generated by Django 6.0.2 on 2026-02-20 11:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_quotation_fabric_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=10)),
                ('yymm', models.CharField(max_length=4)),
                ('last_no', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_docsequence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('order_by', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('style_no', models.CharField(max_length=100)),
                ('job_created_by', models.CharField(default='admin', max_length=100)),
                ('style_name', models.CharField(max_length=200)),
                ('customer_po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('combo', models.CharField(max_length=100)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric_type', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('designer_name', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(default='998821', max_length=20)),
                ('items', models.JSONField(blank=True, default=list, null=True)),
                ('total_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('avg_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('l_confirm_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('h_confirm_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('mistake_details', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approval', models.CharField(default='Pending', max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JobCard',
                'verbose_name_plural': 'JobCards',
                'db_table': 'inventory_jobcard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=200)),
                ('width', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('sq_inch', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('confirmed_amt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('confirmed_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_jobcarditem',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_party',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='fabric_type',
            field=models.CharField(blank=True, default='Domestic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='job_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Reproduction', 'Reproduction'), ('Sample', 'Sample'), ('Sticker', 'Sticker')], default='Production', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='order_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='style_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='amt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='confirmed_amt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_no'], name='inventory_q_quotati_3729f1_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer_name'], name='inventory_q_custome_47e5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['date'], name='inventory_q_date_ff6407_idx'),
        ),
        migrations.AlterModelTable(
            name='quotation',
            table='inventory_quotation',
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table='inventory_quotationitem',
        ),
        migrations.AlterUniqueTogether(
            name='docsequence',
            unique_together={('doc_type', 'yymm')},
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['jobcard_no'], name='inventory_j_jobcard_902b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['customer_name'], name='inventory_j_custome_dc0b75_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['status'], name='inventory_j_status_864ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['created_at'], name='inventory_j_created_40a3ca_idx'),
        ),
        migrations.AddField(
            model_name='jobcarditem',
            name='jobcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_rel', to='Inventory.jobcard'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['name'], name='inventory_p_name_d2fa8a_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['party_no'], name='inventory_p_party_n_257d4c_idx'),
        ),
    ]
